--
-- PostgreSQL database dump
--

-- Dumped from database version 16.3 (Debian 16.3-1.pgdg120+1)
-- Dumped by pg_dump version 17.0

-- Started on 2026-01-03 19:13:37

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 215 (class 1259 OID 24747)
-- Name: AspNetRoleClaims; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AspNetRoleClaims" (
    "Id" integer NOT NULL,
    "RoleId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text
);


ALTER TABLE public."AspNetRoleClaims" OWNER TO postgres;

--
-- TOC entry 216 (class 1259 OID 24752)
-- Name: AspNetRoleClaims_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."AspNetRoleClaims" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."AspNetRoleClaims_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 217 (class 1259 OID 24753)
-- Name: AspNetRoles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AspNetRoles" (
    "Id" text NOT NULL,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text
);


ALTER TABLE public."AspNetRoles" OWNER TO postgres;

--
-- TOC entry 218 (class 1259 OID 24758)
-- Name: AspNetUserClaims; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AspNetUserClaims" (
    "Id" integer NOT NULL,
    "UserId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text
);


ALTER TABLE public."AspNetUserClaims" OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 24763)
-- Name: AspNetUserClaims_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."AspNetUserClaims" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."AspNetUserClaims_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 24764)
-- Name: AspNetUserLogins; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AspNetUserLogins" (
    "LoginProvider" character varying(128) NOT NULL,
    "ProviderKey" character varying(128) NOT NULL,
    "ProviderDisplayName" text,
    "UserId" text NOT NULL
);


ALTER TABLE public."AspNetUserLogins" OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 24769)
-- Name: AspNetUserRoles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AspNetUserRoles" (
    "UserId" text NOT NULL,
    "RoleId" text NOT NULL
);


ALTER TABLE public."AspNetUserRoles" OWNER TO postgres;

--
-- TOC entry 222 (class 1259 OID 24774)
-- Name: AspNetUserTokens; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AspNetUserTokens" (
    "UserId" text NOT NULL,
    "LoginProvider" character varying(128) NOT NULL,
    "Name" character varying(128) NOT NULL,
    "Value" text
);


ALTER TABLE public."AspNetUserTokens" OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 24779)
-- Name: AspNetUsers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AspNetUsers" (
    "Id" text NOT NULL,
    "FullName" text NOT NULL,
    "UserName" character varying(256),
    "NormalizedUserName" character varying(256),
    "Email" character varying(256),
    "NormalizedEmail" character varying(256),
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL
);


ALTER TABLE public."AspNetUsers" OWNER TO postgres;

--
-- TOC entry 224 (class 1259 OID 24784)
-- Name: Categories; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Categories" (
    "Id" uuid NOT NULL,
    "Name" text
);


ALTER TABLE public."Categories" OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 24789)
-- Name: CheckoutOrderItems; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."CheckoutOrderItems" (
    "Id" uuid NOT NULL,
    "ProductId" uuid NOT NULL,
    "Quantity" integer NOT NULL,
    "UserId" text,
    "CreatedOn" timestamp with time zone NOT NULL
);


ALTER TABLE public."CheckoutOrderItems" OWNER TO postgres;

--
-- TOC entry 226 (class 1259 OID 24794)
-- Name: NewsletterSubscribers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."NewsletterSubscribers" (
    "Id" uuid NOT NULL,
    "Email" text NOT NULL,
    "CreatedOn" timestamp with time zone NOT NULL
);


ALTER TABLE public."NewsletterSubscribers" OWNER TO postgres;

--
-- TOC entry 227 (class 1259 OID 24799)
-- Name: OrderLines; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."OrderLines" (
    "Id" uuid NOT NULL,
    "OrderId" uuid NOT NULL,
    "ProductId" uuid NOT NULL,
    "Quantity" integer NOT NULL,
    "UnitPrice" numeric NOT NULL
);


ALTER TABLE public."OrderLines" OWNER TO postgres;

--
-- TOC entry 228 (class 1259 OID 24804)
-- Name: Orders; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Orders" (
    "Id" uuid NOT NULL,
    "UserId" text NOT NULL,
    "Status" text NOT NULL,
    "Reference" text NOT NULL,
    "TotalAmount" numeric NOT NULL,
    "CreatedOn" timestamp with time zone NOT NULL,
    "ShippingCarrier" text,
    "TrackingNumber" text,
    "TrackingUrl" text,
    "ShippingStatus" text NOT NULL,
    "ShippedOn" timestamp with time zone,
    "DeliveredOn" timestamp with time zone,
    "LastTrackingUpdate" timestamp with time zone
);


ALTER TABLE public."Orders" OWNER TO postgres;

--
-- TOC entry 229 (class 1259 OID 24809)
-- Name: PaymentMethods; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."PaymentMethods" (
    "Id" uuid NOT NULL,
    "Name" text NOT NULL
);


ALTER TABLE public."PaymentMethods" OWNER TO postgres;

--
-- TOC entry 230 (class 1259 OID 24814)
-- Name: ProductVariants; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."ProductVariants" (
    "Id" uuid NOT NULL,
    "ProductId" uuid NOT NULL,
    "Sku" character varying(64),
    "SizeScale" integer NOT NULL,
    "SizeValue" character varying(16) NOT NULL,
    "Price" numeric(18,2),
    "Stock" integer NOT NULL,
    "Color" character varying(32),
    "IsDefault" boolean NOT NULL
);


ALTER TABLE public."ProductVariants" OWNER TO postgres;

--
-- TOC entry 231 (class 1259 OID 24817)
-- Name: Products; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Products" (
    "Id" uuid NOT NULL,
    "Name" text,
    "Description" text,
    "Price" numeric(18,2) NOT NULL,
    "Image" text,
    "Quantity" integer NOT NULL,
    "CreatedOn" timestamp with time zone NOT NULL,
    "CategoryId" uuid NOT NULL
);


ALTER TABLE public."Products" OWNER TO postgres;

--
-- TOC entry 232 (class 1259 OID 24822)
-- Name: RefreshTokens; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."RefreshTokens" (
    "Id" uuid NOT NULL,
    "UserId" text NOT NULL,
    "Token" text NOT NULL
);


ALTER TABLE public."RefreshTokens" OWNER TO postgres;

--
-- TOC entry 233 (class 1259 OID 24827)
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO postgres;

--
-- TOC entry 3465 (class 0 OID 24747)
-- Dependencies: 215
-- Data for Name: AspNetRoleClaims; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 3467 (class 0 OID 24753)
-- Dependencies: 217
-- Data for Name: AspNetRoles; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public."AspNetRoles" VALUES ('93f5cdac-43de-4895-8426-2048c228e76d', 'Admin', 'ADMIN', '48f64438-b4e5-4814-b02a-0b82d884c6ac');
INSERT INTO public."AspNetRoles" VALUES ('b7af6842-02fa-4af4-8f61-ae04a49644a2', 'User', 'USER', '4278a124-3255-4579-9957-ab0cc0f530cb');


--
-- TOC entry 3468 (class 0 OID 24758)
-- Dependencies: 218
-- Data for Name: AspNetUserClaims; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 3470 (class 0 OID 24764)
-- Dependencies: 220
-- Data for Name: AspNetUserLogins; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 3471 (class 0 OID 24769)
-- Dependencies: 221
-- Data for Name: AspNetUserRoles; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public."AspNetUserRoles" VALUES ('a8229038-02eb-4c25-a3c8-441bee48f590', '93f5cdac-43de-4895-8426-2048c228e76d');


--
-- TOC entry 3472 (class 0 OID 24774)
-- Dependencies: 222
-- Data for Name: AspNetUserTokens; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 3473 (class 0 OID 24779)
-- Dependencies: 223
-- Data for Name: AspNetUsers; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public."AspNetUsers" VALUES ('a8229038-02eb-4c25-a3c8-441bee48f590', 'Denis', 'den.alexandre@gmail.com', 'DEN.ALEXANDRE@GMAIL.COM', 'den.alexandre@gmail.com', 'DEN.ALEXANDRE@GMAIL.COM', true, 'AQAAAAIAAYagAAAAENvtjsXeaCG0R30CWv+a08JIN7SoM2YagycqzFK1UWGXhUQCvOt8ABcydnDf5/lYlQ==', 'XSEHZLTP32Z52E4KRHIHKS55IEZAOL6T', 'e1523a71-adec-4d12-9407-18f76d00fdcd', NULL, false, false, NULL, true, 0);


--
-- TOC entry 3474 (class 0 OID 24784)
-- Dependencies: 224
-- Data for Name: Categories; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public."Categories" VALUES ('99b5df05-15da-44be-adda-f7933bcd9911', 'Menus');
INSERT INTO public."Categories" VALUES ('babbc6b7-2124-4912-b338-1e4a7a00a642', 'Burgers');
INSERT INTO public."Categories" VALUES ('7bcade30-0b39-4b2e-892f-6d062ef87559', 'Sandwitchs');
INSERT INTO public."Categories" VALUES ('d846bb80-c601-4d03-bb6f-be5374958d3a', 'Frites');
INSERT INTO public."Categories" VALUES ('4f63b8eb-c164-41b0-a9c9-7338744a63ef', 'Sauces');
INSERT INTO public."Categories" VALUES ('9ef59d5b-f1dd-4752-a840-90faf7c6b5f6', 'Viandes');
INSERT INTO public."Categories" VALUES ('f57f16c3-4fa8-4af1-ba8c-81bf3a0dc833', 'All');


--
-- TOC entry 3475 (class 0 OID 24789)
-- Dependencies: 225
-- Data for Name: CheckoutOrderItems; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 3476 (class 0 OID 24794)
-- Dependencies: 226
-- Data for Name: NewsletterSubscribers; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 3477 (class 0 OID 24799)
-- Dependencies: 227
-- Data for Name: OrderLines; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 3478 (class 0 OID 24804)
-- Dependencies: 228
-- Data for Name: Orders; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 3479 (class 0 OID 24809)
-- Dependencies: 229
-- Data for Name: PaymentMethods; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public."PaymentMethods" VALUES ('3604fc1d-cd6a-46ad-ace4-9b5f8e03f43b', 'Credit Card');
INSERT INTO public."PaymentMethods" VALUES ('6f2c2a7e-9f9b-4a0d-9f7f-2a1b3c4d5e6f', 'Cash on Delivery');
INSERT INTO public."PaymentMethods" VALUES ('a3bb23e6-6a7c-4b7d-9c73-7d5f2bc2f7b1', 'PayPal');
INSERT INTO public."PaymentMethods" VALUES ('b2e5c1d4-7a9f-4d2c-8f1e-3a4b5c6d7e8f', 'Bank Transfer');


--
-- TOC entry 3480 (class 0 OID 24814)
-- Dependencies: 230
-- Data for Name: ProductVariants; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 3481 (class 0 OID 24817)
-- Dependencies: 231
-- Data for Name: Products; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public."Products" VALUES ('c94ad571-2814-4723-9fab-c4e37f9bb24b', 'Rosty Burger', 'Le bon Rosty comme avant', 7.50, 'images/burgers/burger1.jpg', 10, '2025-12-31 09:42:10.58233+00', 'babbc6b7-2124-4912-b338-1e4a7a00a642');
INSERT INTO public."Products" VALUES ('0ce060e8-f505-4c02-879a-94ca4b013fa6', 'Burger Montagnard', 'Le bon Montagnard comme avant', 6.00, 'images/burgers/burger2.jpg', 10, '2025-12-31 09:45:07.231011+00', 'babbc6b7-2124-4912-b338-1e4a7a00a642');


--
-- TOC entry 3482 (class 0 OID 24822)
-- Dependencies: 232
-- Data for Name: RefreshTokens; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public."RefreshTokens" VALUES ('a3f0041b-7513-4953-8331-2efd15c9b48c', 'a8229038-02eb-4c25-a3c8-441bee48f590', '2geFT4Fy85he15lvpMaGuzukbk7k9aQzNNVZD1XamINB2vIHNqcy8mXQJcCecHKoOiaQlztNZOGE8FVVZQw9hw%3D%3D');
INSERT INTO public."RefreshTokens" VALUES ('3f42b8a8-c205-40f2-84f3-33d05c34aab7', 'a8229038-02eb-4c25-a3c8-441bee48f590', 'lX4qd10hh24E0v7AfiSuUoTJycANbP68ShdwfvIBVSNMCaRsp%2BReFs5KKc%2B%2FVpSxeAltClZQ1NW0OzZiQWhcXw%3D%3D');


--
-- TOC entry 3483 (class 0 OID 24827)
-- Dependencies: 233
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 3489 (class 0 OID 0)
-- Dependencies: 216
-- Name: AspNetRoleClaims_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."AspNetRoleClaims_Id_seq"', 1, false);


--
-- TOC entry 3490 (class 0 OID 0)
-- Dependencies: 219
-- Name: AspNetUserClaims_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."AspNetUserClaims_Id_seq"', 1, false);


--
-- TOC entry 3270 (class 2606 OID 24831)
-- Name: AspNetRoleClaims PK_AspNetRoleClaims; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetRoleClaims"
    ADD CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id");


--
-- TOC entry 3272 (class 2606 OID 24833)
-- Name: AspNetRoles PK_AspNetRoles; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetRoles"
    ADD CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id");


--
-- TOC entry 3276 (class 2606 OID 24835)
-- Name: AspNetUserClaims PK_AspNetUserClaims; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserClaims"
    ADD CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id");


--
-- TOC entry 3279 (class 2606 OID 24837)
-- Name: AspNetUserLogins PK_AspNetUserLogins; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserLogins"
    ADD CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey");


--
-- TOC entry 3282 (class 2606 OID 24839)
-- Name: AspNetUserRoles PK_AspNetUserRoles; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserRoles"
    ADD CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId");


--
-- TOC entry 3284 (class 2606 OID 24841)
-- Name: AspNetUserTokens PK_AspNetUserTokens; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserTokens"
    ADD CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name");


--
-- TOC entry 3287 (class 2606 OID 24843)
-- Name: AspNetUsers PK_AspNetUsers; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUsers"
    ADD CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id");


--
-- TOC entry 3290 (class 2606 OID 24845)
-- Name: Categories PK_Categories; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Categories"
    ADD CONSTRAINT "PK_Categories" PRIMARY KEY ("Id");


--
-- TOC entry 3292 (class 2606 OID 24847)
-- Name: CheckoutOrderItems PK_CheckoutOrderItems; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."CheckoutOrderItems"
    ADD CONSTRAINT "PK_CheckoutOrderItems" PRIMARY KEY ("Id");


--
-- TOC entry 3295 (class 2606 OID 24849)
-- Name: NewsletterSubscribers PK_NewsletterSubscribers; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."NewsletterSubscribers"
    ADD CONSTRAINT "PK_NewsletterSubscribers" PRIMARY KEY ("Id");


--
-- TOC entry 3298 (class 2606 OID 24851)
-- Name: OrderLines PK_OrderLines; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."OrderLines"
    ADD CONSTRAINT "PK_OrderLines" PRIMARY KEY ("Id");


--
-- TOC entry 3300 (class 2606 OID 24853)
-- Name: Orders PK_Orders; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Orders"
    ADD CONSTRAINT "PK_Orders" PRIMARY KEY ("Id");


--
-- TOC entry 3302 (class 2606 OID 24855)
-- Name: PaymentMethods PK_PaymentMethods; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."PaymentMethods"
    ADD CONSTRAINT "PK_PaymentMethods" PRIMARY KEY ("Id");


--
-- TOC entry 3305 (class 2606 OID 24857)
-- Name: ProductVariants PK_ProductVariants; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."ProductVariants"
    ADD CONSTRAINT "PK_ProductVariants" PRIMARY KEY ("Id");


--
-- TOC entry 3308 (class 2606 OID 24859)
-- Name: Products PK_Products; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Products"
    ADD CONSTRAINT "PK_Products" PRIMARY KEY ("Id");


--
-- TOC entry 3310 (class 2606 OID 24861)
-- Name: RefreshTokens PK_RefreshTokens; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."RefreshTokens"
    ADD CONSTRAINT "PK_RefreshTokens" PRIMARY KEY ("Id");


--
-- TOC entry 3312 (class 2606 OID 24863)
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- TOC entry 3285 (class 1259 OID 24864)
-- Name: EmailIndex; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "EmailIndex" ON public."AspNetUsers" USING btree ("NormalizedEmail");


--
-- TOC entry 3268 (class 1259 OID 24865)
-- Name: IX_AspNetRoleClaims_RoleId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON public."AspNetRoleClaims" USING btree ("RoleId");


--
-- TOC entry 3274 (class 1259 OID 24866)
-- Name: IX_AspNetUserClaims_UserId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_AspNetUserClaims_UserId" ON public."AspNetUserClaims" USING btree ("UserId");


--
-- TOC entry 3277 (class 1259 OID 24867)
-- Name: IX_AspNetUserLogins_UserId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_AspNetUserLogins_UserId" ON public."AspNetUserLogins" USING btree ("UserId");


--
-- TOC entry 3280 (class 1259 OID 24868)
-- Name: IX_AspNetUserRoles_RoleId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_AspNetUserRoles_RoleId" ON public."AspNetUserRoles" USING btree ("RoleId");


--
-- TOC entry 3293 (class 1259 OID 24869)
-- Name: IX_NewsletterSubscribers_Email; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_NewsletterSubscribers_Email" ON public."NewsletterSubscribers" USING btree ("Email");


--
-- TOC entry 3296 (class 1259 OID 24870)
-- Name: IX_OrderLines_OrderId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_OrderLines_OrderId" ON public."OrderLines" USING btree ("OrderId");


--
-- TOC entry 3303 (class 1259 OID 24871)
-- Name: IX_ProductVariants_ProductId_SizeScale_SizeValue; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_ProductVariants_ProductId_SizeScale_SizeValue" ON public."ProductVariants" USING btree ("ProductId", "SizeScale", "SizeValue");


--
-- TOC entry 3306 (class 1259 OID 24872)
-- Name: IX_Products_CategoryId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Products_CategoryId" ON public."Products" USING btree ("CategoryId");


--
-- TOC entry 3273 (class 1259 OID 24873)
-- Name: RoleNameIndex; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "RoleNameIndex" ON public."AspNetRoles" USING btree ("NormalizedName");


--
-- TOC entry 3288 (class 1259 OID 24874)
-- Name: UserNameIndex; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "UserNameIndex" ON public."AspNetUsers" USING btree ("NormalizedUserName");


--
-- TOC entry 3313 (class 2606 OID 24875)
-- Name: AspNetRoleClaims FK_AspNetRoleClaims_AspNetRoles_RoleId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetRoleClaims"
    ADD CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES public."AspNetRoles"("Id") ON DELETE CASCADE;


--
-- TOC entry 3314 (class 2606 OID 24880)
-- Name: AspNetUserClaims FK_AspNetUserClaims_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserClaims"
    ADD CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- TOC entry 3315 (class 2606 OID 24885)
-- Name: AspNetUserLogins FK_AspNetUserLogins_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserLogins"
    ADD CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- TOC entry 3316 (class 2606 OID 24890)
-- Name: AspNetUserRoles FK_AspNetUserRoles_AspNetRoles_RoleId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserRoles"
    ADD CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES public."AspNetRoles"("Id") ON DELETE CASCADE;


--
-- TOC entry 3317 (class 2606 OID 24895)
-- Name: AspNetUserRoles FK_AspNetUserRoles_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserRoles"
    ADD CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- TOC entry 3318 (class 2606 OID 24900)
-- Name: AspNetUserTokens FK_AspNetUserTokens_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserTokens"
    ADD CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- TOC entry 3319 (class 2606 OID 24905)
-- Name: OrderLines FK_OrderLines_Orders_OrderId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."OrderLines"
    ADD CONSTRAINT "FK_OrderLines_Orders_OrderId" FOREIGN KEY ("OrderId") REFERENCES public."Orders"("Id") ON DELETE CASCADE;


--
-- TOC entry 3320 (class 2606 OID 24910)
-- Name: ProductVariants FK_ProductVariants_Products_ProductId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."ProductVariants"
    ADD CONSTRAINT "FK_ProductVariants_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES public."Products"("Id") ON DELETE CASCADE;


--
-- TOC entry 3321 (class 2606 OID 24915)
-- Name: Products FK_Products_Categories_CategoryId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Products"
    ADD CONSTRAINT "FK_Products_Categories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES public."Categories"("Id") ON DELETE CASCADE;


-- Completed on 2026-01-03 19:13:38

--
-- PostgreSQL database dump complete
--

