-- Script d'initialisation pour Neon (schema + données essentielles)
-- Les produits et catégories seront ajoutés par le SampleDataSeeder

SET statement_timeout = 0;
SET lock_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);

SET default_tablespace = '';
SET default_table_access_method = heap;

-- ══════════════════════════════════════
-- TABLES
-- ══════════════════════════════════════

CREATE TABLE public."AspNetRoleClaims" (
    "Id" integer NOT NULL,
    "RoleId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text
);

ALTER TABLE public."AspNetRoleClaims" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."AspNetRoleClaims_Id_seq"
    START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

CREATE TABLE public."AspNetRoles" (
    "Id" text NOT NULL,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text
);

CREATE TABLE public."AspNetUserClaims" (
    "Id" integer NOT NULL,
    "UserId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text
);

ALTER TABLE public."AspNetUserClaims" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."AspNetUserClaims_Id_seq"
    START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

CREATE TABLE public."AspNetUserLogins" (
    "LoginProvider" character varying(128) NOT NULL,
    "ProviderKey" character varying(128) NOT NULL,
    "ProviderDisplayName" text,
    "UserId" text NOT NULL
);

CREATE TABLE public."AspNetUserRoles" (
    "UserId" text NOT NULL,
    "RoleId" text NOT NULL
);

CREATE TABLE public."AspNetUserTokens" (
    "UserId" text NOT NULL,
    "LoginProvider" character varying(128) NOT NULL,
    "Name" character varying(128) NOT NULL,
    "Value" text
);

CREATE TABLE public."AspNetUsers" (
    "Id" text NOT NULL,
    "FullName" text NOT NULL,
    "UserName" character varying(256),
    "NormalizedUserName" character varying(256),
    "Email" character varying(256),
    "NormalizedEmail" character varying(256),
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL
);

CREATE TABLE public."Categories" (
    "Id" uuid NOT NULL,
    "Name" text
);

CREATE TABLE public."CheckoutOrderItems" (
    "Id" uuid NOT NULL,
    "ProductId" uuid NOT NULL,
    "Quantity" integer NOT NULL,
    "UserId" text,
    "CreatedOn" timestamp with time zone NOT NULL
);

CREATE TABLE public."NewsletterSubscribers" (
    "Id" uuid NOT NULL,
    "Email" text NOT NULL,
    "CreatedOn" timestamp with time zone NOT NULL
);

CREATE TABLE public."OrderLines" (
    "Id" uuid NOT NULL,
    "OrderId" uuid NOT NULL,
    "ProductId" uuid NOT NULL,
    "Quantity" integer NOT NULL,
    "UnitPrice" numeric NOT NULL
);

CREATE TABLE public."Orders" (
    "Id" uuid NOT NULL,
    "UserId" text NOT NULL,
    "Status" text NOT NULL,
    "Reference" text NOT NULL,
    "TotalAmount" numeric NOT NULL,
    "CreatedOn" timestamp with time zone NOT NULL,
    "ShippingCarrier" text,
    "TrackingNumber" text,
    "TrackingUrl" text,
    "ShippingStatus" text NOT NULL,
    "ShippedOn" timestamp with time zone,
    "DeliveredOn" timestamp with time zone,
    "LastTrackingUpdate" timestamp with time zone
);

CREATE TABLE public."PaymentMethods" (
    "Id" uuid NOT NULL,
    "Name" text NOT NULL
);

CREATE TABLE public."ProductVariants" (
    "Id" uuid NOT NULL,
    "ProductId" uuid NOT NULL,
    "Sku" character varying(64),
    "SizeScale" integer NOT NULL,
    "SizeValue" character varying(16) NOT NULL,
    "Price" numeric(18,2),
    "Stock" integer NOT NULL,
    "Color" character varying(32),
    "IsDefault" boolean NOT NULL
);

CREATE TABLE public."Products" (
    "Id" uuid NOT NULL,
    "Name" text,
    "Description" text,
    "Price" numeric(18,2) NOT NULL,
    "Image" text,
    "Quantity" integer NOT NULL,
    "CreatedOn" timestamp with time zone NOT NULL,
    "CategoryId" uuid NOT NULL
);

CREATE TABLE public."RefreshTokens" (
    "Id" uuid NOT NULL,
    "UserId" text NOT NULL,
    "Token" text NOT NULL
);

-- ══════════════════════════════════════
-- PRIMARY KEYS
-- ══════════════════════════════════════

ALTER TABLE ONLY public."AspNetRoleClaims" ADD CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id");
ALTER TABLE ONLY public."AspNetRoles" ADD CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id");
ALTER TABLE ONLY public."AspNetUserClaims" ADD CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id");
ALTER TABLE ONLY public."AspNetUserLogins" ADD CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey");
ALTER TABLE ONLY public."AspNetUserRoles" ADD CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId");
ALTER TABLE ONLY public."AspNetUserTokens" ADD CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name");
ALTER TABLE ONLY public."AspNetUsers" ADD CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id");
ALTER TABLE ONLY public."Categories" ADD CONSTRAINT "PK_Categories" PRIMARY KEY ("Id");
ALTER TABLE ONLY public."CheckoutOrderItems" ADD CONSTRAINT "PK_CheckoutOrderItems" PRIMARY KEY ("Id");
ALTER TABLE ONLY public."NewsletterSubscribers" ADD CONSTRAINT "PK_NewsletterSubscribers" PRIMARY KEY ("Id");
ALTER TABLE ONLY public."OrderLines" ADD CONSTRAINT "PK_OrderLines" PRIMARY KEY ("Id");
ALTER TABLE ONLY public."Orders" ADD CONSTRAINT "PK_Orders" PRIMARY KEY ("Id");
ALTER TABLE ONLY public."PaymentMethods" ADD CONSTRAINT "PK_PaymentMethods" PRIMARY KEY ("Id");
ALTER TABLE ONLY public."ProductVariants" ADD CONSTRAINT "PK_ProductVariants" PRIMARY KEY ("Id");
ALTER TABLE ONLY public."Products" ADD CONSTRAINT "PK_Products" PRIMARY KEY ("Id");
ALTER TABLE ONLY public."RefreshTokens" ADD CONSTRAINT "PK_RefreshTokens" PRIMARY KEY ("Id");

-- ══════════════════════════════════════
-- INDEXES
-- ══════════════════════════════════════

CREATE INDEX "EmailIndex" ON public."AspNetUsers" USING btree ("NormalizedEmail");
CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON public."AspNetRoleClaims" USING btree ("RoleId");
CREATE INDEX "IX_AspNetUserClaims_UserId" ON public."AspNetUserClaims" USING btree ("UserId");
CREATE INDEX "IX_AspNetUserLogins_UserId" ON public."AspNetUserLogins" USING btree ("UserId");
CREATE INDEX "IX_AspNetUserRoles_RoleId" ON public."AspNetUserRoles" USING btree ("RoleId");
CREATE UNIQUE INDEX "IX_NewsletterSubscribers_Email" ON public."NewsletterSubscribers" USING btree ("Email");
CREATE INDEX "IX_OrderLines_OrderId" ON public."OrderLines" USING btree ("OrderId");
CREATE UNIQUE INDEX "IX_ProductVariants_ProductId_SizeScale_SizeValue" ON public."ProductVariants" USING btree ("ProductId", "SizeScale", "SizeValue");
CREATE INDEX "IX_Products_CategoryId" ON public."Products" USING btree ("CategoryId");
CREATE UNIQUE INDEX "RoleNameIndex" ON public."AspNetRoles" USING btree ("NormalizedName");
CREATE UNIQUE INDEX "UserNameIndex" ON public."AspNetUsers" USING btree ("NormalizedUserName");

-- ══════════════════════════════════════
-- FOREIGN KEYS
-- ══════════════════════════════════════

ALTER TABLE ONLY public."AspNetRoleClaims" ADD CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES public."AspNetRoles"("Id") ON DELETE CASCADE;
ALTER TABLE ONLY public."AspNetUserClaims" ADD CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;
ALTER TABLE ONLY public."AspNetUserLogins" ADD CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;
ALTER TABLE ONLY public."AspNetUserRoles" ADD CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES public."AspNetRoles"("Id") ON DELETE CASCADE;
ALTER TABLE ONLY public."AspNetUserRoles" ADD CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;
ALTER TABLE ONLY public."AspNetUserTokens" ADD CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;
ALTER TABLE ONLY public."OrderLines" ADD CONSTRAINT "FK_OrderLines_Orders_OrderId" FOREIGN KEY ("OrderId") REFERENCES public."Orders"("Id") ON DELETE CASCADE;
ALTER TABLE ONLY public."ProductVariants" ADD CONSTRAINT "FK_ProductVariants_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES public."Products"("Id") ON DELETE CASCADE;
ALTER TABLE ONLY public."Products" ADD CONSTRAINT "FK_Products_Categories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES public."Categories"("Id") ON DELETE CASCADE;

-- ══════════════════════════════════════
-- DONNÉES ESSENTIELLES (Rôles, Utilisateurs, Paiements)
-- ══════════════════════════════════════

-- Rôles
INSERT INTO public."AspNetRoles" VALUES ('93f5cdac-43de-4895-8426-2048c228e76d', 'Admin', 'ADMIN', '48f64438-b4e5-4814-b02a-0b82d884c6ac');
INSERT INTO public."AspNetRoles" VALUES ('b7af6842-02fa-4af4-8f61-ae04a49644a2', 'User', 'USER', '4278a124-3255-4579-9957-ab0cc0f530cb');
INSERT INTO public."AspNetRoles" VALUES ('c1d2e3f4-5a6b-7c8d-9e0f-1a2b3c4d5e6f', 'Cuisine', 'CUISINE', '648aed6a-307e-45dd-b429-188e3f3b8408');

-- Utilisateurs
INSERT INTO public."AspNetUsers" VALUES ('a8229038-02eb-4c25-a3c8-441bee48f590', 'Denis', 'den.alexandre@gmail.com', 'DEN.ALEXANDRE@GMAIL.COM', 'den.alexandre@gmail.com', 'DEN.ALEXANDRE@GMAIL.COM', true, 'AQAAAAIAAYagAAAAENvtjsXeaCG0R30CWv+a08JIN7SoM2YagycqzFK1UWGXhUQCvOt8ABcydnDf5/lYlQ==', 'XSEHZLTP32Z52E4KRHIHKS55IEZAOL6T', 'e1523a71-adec-4d12-9407-18f76d00fdcd', NULL, false, false, NULL, true, 0);
INSERT INTO public."AspNetUsers" VALUES ('e2b049e5-ef3f-4548-9fd5-6277e88fb72b', 'John', 'john.alexandre@gmail.com', 'JOHN.ALEXANDRE@GMAIL.COM', 'john.alexandre@gmail.com', 'JOHN.ALEXANDRE@GMAIL.COM', true, 'AQAAAAIAAYagAAAAEF3rIGqLWPeWnpjutGJIhQEHEzOXcxFreUaRtm5OJeG3GXx4R7xcckx3ryF9D5AgPA==', 'BVQBQG52HET6HKDGLIVNMXP5BGIWRTVV', '0826eae0-2b11-4256-a29b-fba7105fe3fc', NULL, false, false, NULL, true, 0);

-- Rôles utilisateurs (Denis=Admin, John=Cuisine)
INSERT INTO public."AspNetUserRoles" VALUES ('a8229038-02eb-4c25-a3c8-441bee48f590', '93f5cdac-43de-4895-8426-2048c228e76d');
INSERT INTO public."AspNetUserRoles" VALUES ('e2b049e5-ef3f-4548-9fd5-6277e88fb72b', 'c1d2e3f4-5a6b-7c8d-9e0f-1a2b3c4d5e6f');

-- Moyens de paiement
INSERT INTO public."PaymentMethods" VALUES ('3604fc1d-cd6a-46ad-ace4-9b5f8e03f43b', 'Credit Card');
INSERT INTO public."PaymentMethods" VALUES ('6f2c2a7e-9f9b-4a0d-9f7f-2a1b3c4d5e6f', 'Cash on Delivery');
INSERT INTO public."PaymentMethods" VALUES ('a3bb23e6-6a7c-4b7d-9c73-7d5f2bc2f7b1', 'PayPal');
INSERT INTO public."PaymentMethods" VALUES ('b2e5c1d4-7a9f-4d2c-8f1e-3a4b5c6d7e8f', 'Bank Transfer');

-- Les produits et catégories seront ajoutés automatiquement par le SampleDataSeeder au démarrage de l'API
